---
- name: Ensure dependencies are installed.
  package: name={{ item }} state=present
  with_items:
    - lsof
    - acl
    - sudo

- name: Run Solr installation script.
  command: >
    {{ solr_workspace }}/{{ solr_filename }}/bin/install_solr_service.sh
    {{ solr_workspace }}/{{ solr_filename }}.tgz
    -i {{ solr_install_dir }}
    -d {{ solr_home }}
    -u {{ solr_user }}
    -s {{ solr_service_name }}
    -p {{ solr_port }}
    creates={{ solr_install_path }}/bin/solr
  notify:
    - Ensure solr is stopped (RHEL 7 workaround).
    - Run systemd daemon_reload (RHEL 7 workaround).
    - Ensure solr is started and enabled on boot if configured.

- name: Flush Handlers.
  meta: flush_handlers
